sudo: required
services:
  - docker

before_install:
  - docker build -t joshnavru/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true joshnavru/react-test npm test

after_success:
  - docker build -t joshnavru/multi-client ./client
  - docker build -t joshnavru/multi-nginx ./nginx
  - docker build -t joshnavru/multi-server ./server
  - docker build -t joshnavru/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push joshnavru/multi-client
  - docker push joshnavru/multi-nginx
  - docker push joshnavru/multi-server
  - docker push joshnavru/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-us-east-1-403967370966
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
